### ISSUE TITLE
Fix old tests with new framework

### ISSUE THREAD

**Issue by dpaiton** [element-fi/elf-simulations#31]
Dev currently does not pass CI because the tests are mostly broken with the refactor. We need to go through each commented test and fix it so that it passes, or delete it if it is no longer relevant.

**Comment by wakamex** [comment]
the use of a test harness in 2 functions in test_pricing_model.py means on a failed test you have no idea which one it is. pytest spits out the name of the function, which in this case contains 16 tests. Is the standard to split each test out into 1 function?

**Comment by wakamex** [comment]
I noticed that by using a helper function of `compare_results` that pytests's error printout isn't very useful, since it just prints a few lines from that helper function, instead of from the actual test. pytest also tries to print useful local variables, but in this case, there aren't any useful ones within this function.

**Comment by dpaiton** [comment]
@jalextowle for your fix can you change the `calc_in_given_out` and `calc_out_given_in` tests to only check for the existence of an error message, instead of checking for the exact text of the error message? We want to be able to change up messaging without much fuss.

**Comment by wakamex** [comment]
I think this is done, right?
